project:
  type: website
  output-dir: docs

  

website:
  title: "jennabraun.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - research.qmd


format:
  html:
    theme: journal
    css: styles.css
    toc: true
    include-in-header: analytics.html

editor: visual

